haproxy:
    build: .
    ports:
        - "443:443"
    volumes:
        - ./server.pem:/usr/local/etc/haproxy/server.pem
        - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
        - ./ca.crt:/usr/local/etc/haproxy/ca.crt
